/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-11-07 00:32:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.inc;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <title>Happynimal</title>\r\n");
      out.write("        <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("        <meta content=\"\" name=\"keywords\">\r\n");
      out.write("        <meta content=\"\" name=\"description\">\r\n");
      out.write("        <link rel=\"icon\" href=\"/pet/resources/img/favicon.png\">\r\n");
      out.write("        <!-- Google Web Fonts -->\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <!-- Icon Font Stylesheet -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.15.4/css/all.css\"/>\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Libraries Stylesheet -->\r\n");
      out.write("        <link href=\"/pet/resources/lib/animate/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"/pet/resources/lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("        <link href=\"/pet/resources/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Template Stylesheet -->\r\n");
      out.write("        <link href=\"/pet/resources/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("        <!-- Spinner Start -->\r\n");
      out.write("        <div id=\"spinner\" class=\"show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center\">\r\n");
      out.write("            <div class=\"spinner-border text-primary\" style=\"width: 3rem; height: 3rem;\" role=\"status\">\r\n");
      out.write("                <span class=\"sr-only\">Loading...</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Spinner End -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Navbar & Hero Start -->\r\n");
      out.write("        <div class=\"container-fluid position-relative p-0\">\r\n");
      out.write("            <nav class=\"navbar navbar-expand-lg navbar-light px-4 px-lg-5 py-3 py-lg-0\">\r\n");
      out.write("                <a href=\"/pet/index.do\" class=\"navbar-brand p-0\">\r\n");
      out.write("                    <h1 class=\"text-primary\"><img src=\"/pet/resources/img/logo2.png\"></img>Happynimal</h1>\r\n");
      out.write("                    <!-- <img src=\"img/logo.png\" alt=\"Logo\"> -->\r\n");
      out.write("                </a>\r\n");
      out.write("                <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarCollapse\">\r\n");
      out.write("                    <span class=\"fa fa-bars\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarCollapse\">\r\n");
      out.write("                    <div class=\"navbar-nav ms-auto py-0\">\r\n");
      out.write("                        <a href=\"/pet/index.do\" class=\"nav-item nav-link active\">Home</a>\r\n");
      out.write("                        <a href=\"/pet/about.do\" class=\"nav-item nav-link\">소개</a>\r\n");
      out.write("                        <div class=\"nav-item dropdown\">\r\n");
      out.write("                            <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">입양</a>\r\n");
      out.write("                            <div class=\"dropdown-menu m-0\">\r\n");
      out.write("                                <a href=\"/pet/adoptioninfo.do\" class=\"dropdown-item\">입양안내</a>\r\n");
      out.write("                                <a href=\"/pet/petboard.do\" class=\"dropdown-item\">기다리는 친구들</a>\r\n");
      out.write("                                <a href=\"/pet/applicationadoption.do\" class=\"dropdown-item\">입양신청</a>\r\n");
      out.write("                                <a href=\"/pet/review.do\" class=\"dropdown-item\">입양후기</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("        \r\n");
      out.write("                        <div class=\"nav-item dropdown\">\r\n");
      out.write("                            <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">활동</a>\r\n");
      out.write("                            <div class=\"dropdown-menu m-0\">\r\n");
      out.write("                                <a href=\"/pet/volunteerinfo.do\" class=\"dropdown-item\">봉사활동 안내</a>\r\n");
      out.write("                                <a href=\"/pet/volunteerboard.do\" class=\"dropdown-item\">봉사활동 모집</a>\r\n");
      out.write("                                <a href=\"/pet/missingboard.do\" class=\"dropdown-item\">실종 게시판</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <a href=\"/pet/shelter.do\" class=\"nav-item nav-link\">보호소 및 병원</a>\r\n");
      out.write("                        <a href=\"/pet/donation.do\" class=\"nav-item nav-link\">후원</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"d-none d-xl-flex me-3\">\r\n");
      out.write("                        <div class=\"d-flex flex-column pe-3 border-end border-primary\">\r\n");
      out.write("                           \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <a href=\"\" class=\"btn btn-primary rounded-pill d-inline-flex flex-shrink-0 py-2 px-4\">로그인</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("\r\n");
      out.write("            <!-- Carousel Start -->\r\n");
      out.write("            <div class=\"carousel-header\">\r\n");
      out.write("                <div id=\"carouselId\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("                    <ol class=\"carousel-indicators\">\r\n");
      out.write("                        <li data-bs-target=\"#carouselId\" data-bs-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("                        <li data-bs-target=\"#carouselId\" data-bs-slide-to=\"1\"></li>\r\n");
      out.write("                        <li data-bs-target=\"#carouselId\" data-bs-slide-to=\"2\"></li>\r\n");
      out.write("                    </ol>\r\n");
      out.write("                    <div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("                        <div class=\"carousel-item active\">\r\n");
      out.write("                            <img src=\"/pet/resources/img/dog and volunteer.jpg\" class=\"img-fluid w-100\" alt=\"Image\">\r\n");
      out.write("                            <div class=\"carousel-caption-1\">\r\n");
      out.write("                                <div class=\"carousel-caption-1-content\" style=\"max-width: 900px;\">\r\n");
      out.write("                                    <h4 class=\"text-white text-uppercase fw-bold mb-4 fadeInLeft animated\" data-animation=\"fadeInLeft\" data-delay=\"1s\" style=\"animation-delay: 1s;\" style=\"letter-spacing: 3px;\">환영해요 !</h4>\r\n");
      out.write("                                    <h1 class=\"display-2 text-capitalize text-white mb-4 fadeInLeft animated\" data-animation=\"fadeInLeft\" data-delay=\"1.3s\" style=\"animation-delay: 1.3s;\">Happynimal</h1>\r\n");
      out.write("                                    <p class=\"mb-5 fs-5 text-white fadeInLeft animated\" data-animation=\"fadeInLeft\" data-delay=\"1.5s\" style=\"animation-delay: 1.5s;\">사지말고 <font size=\"6\" color=\"#FF9100\">입양</font>하세요\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                    <div class=\"carousel-caption-1-content-btn fadeInLeft animated\" data-animation=\"fadeInLeft\" data-delay=\"1.7s\" style=\"animation-delay: 1.7s;\">\r\n");
      out.write("                                        <a class=\"btn btn-primary rounded-pill flex-shrink-0 py-3 px-5 me-2\" href=\"#\">입양하기</a>\r\n");
      out.write("                                        <a class=\"btn btn-secondary rounded-pill flex-shrink-0 py-3 px-5 ms-2\" href=\"#\">봉사활동 신청</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"carousel-item\">\r\n");
      out.write("                            <img src=\"/pet/resources/img/rescue.jpg\" class=\"img-fluid w-100\" alt=\"Image\">\r\n");
      out.write("                            <div class=\"carousel-caption-2\">\r\n");
      out.write("                                <div class=\"carousel-caption-2-content\" style=\"max-width: 900px;\">\r\n");
      out.write("                                    <h4 class=\"text-white text-uppercase fw-bold mb-4 fadeInRight animated\" data-animation=\"fadeInRight\" data-delay=\"1s\" style=\"animation-delay: 1s;\" style=\"letter-spacing: 3px;\">환영해요 !</h4>\r\n");
      out.write("                                    <h1 class=\"display-2 text-capitalize text-white mb-4 fadeInRight animated\" data-animation=\"fadeInRight\" data-delay=\"1.3s\" style=\"animation-delay: 1.3s;\">Happynimal</h1>\r\n");
      out.write("                                    <p class=\"mb-5 fs-5 text-white fadeInRight animated\" data-animation=\"fadeInRight\" data-delay=\"1.5s\" style=\"animation-delay: 1.5s;\">사지말고 <font size=\"6\" color=\"#FF9100\">입양</font>하세요\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                    <div class=\"carousel-caption-2-content-btn fadeInRight animated\" data-animation=\"fadeInRight\" data-delay=\"1.7s\" style=\"animation-delay: 1.7s;\">\r\n");
      out.write("                                        <a class=\"btn btn-primary rounded-pill flex-shrink-0 py-3 px-5 me-2\" href=\"#\">입양후기</a>\r\n");
      out.write("                                        <a class=\"btn btn-secondary rounded-pill flex-shrink-0 py-3 px-5 ms-2\" href=\"#\">봉사활동</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselId\" data-bs-slide=\"prev\">\r\n");
      out.write("                        <span class=\"carousel-control-prev-icon btn btn-primary fadeInLeft animated\" aria-hidden=\"true\" data-animation=\"fadeInLeft\" data-delay=\"1.1s\" style=\"animation-delay: 1.3s;\"> <i class=\"fa fa-angle-left fa-3x\"></i></span>\r\n");
      out.write("                        <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselId\" data-bs-slide=\"next\">\r\n");
      out.write("                        <span class=\"carousel-control-next-icon btn btn-primary fadeInRight animated\" aria-hidden=\"true\" data-animation=\"fadeInLeft\" data-delay=\"1.1s\" style=\"animation-delay: 1.3s;\"><i class=\"fa fa-angle-right fa-3x\"></i></span>\r\n");
      out.write("                        <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Carousel End -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Navbar & Hero End -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Modal Search Start -->\r\n");
      out.write("        <div class=\"modal fade\" id=\"searchModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-fullscreen\">\r\n");
      out.write("                <div class=\"modal-content rounded-0\">\r\n");
      out.write("                    <div class=\"modal-header\">\r\n");
      out.write("                        <h4 class=\"modal-title mb-0\" id=\"exampleModalLabel\">Search by keyword</h4>\r\n");
      out.write("                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-body d-flex align-items-center\">\r\n");
      out.write("                        <div class=\"input-group w-75 mx-auto d-flex\">\r\n");
      out.write("                            <input type=\"search\" class=\"form-control p-3\" placeholder=\"keywords\" aria-describedby=\"search-icon-1\">\r\n");
      out.write("                            <span id=\"search-icon-1\" class=\"input-group-text btn border p-3\"><i class=\"fa fa-search text-white\"></i></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Modal Search End -->\r\n");
      out.write("\r\n");
      out.write("        <!-- feature Start -->\r\n");
      out.write("        <div class=\"container-fluid feature bg-light py-5\">\r\n");
      out.write("            <div class=\"container py-5\">\r\n");
      out.write("                <div class=\"text-center mx-auto pb-5 wow fadeInUp\" data-wow-delay=\"0.2s\" style=\"max-width: 800px;\">\r\n");
      out.write("                    <h4 class=\"text-uppercase text-primary\">우리 아이들은 단지 '동물'이 아닙니다.</h4>\r\n");
      out.write("                    <h3 class=\"display-3 text-capitalize mb-3\">사랑받을 자격이 있는 가족입니다.</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row g-4\">\r\n");
      out.write("                    <div class=\" col-md-6 col-lg-6 col-xl-3 wow fadeInUp\" data-wow-delay=\"0.2s\">\r\n");
      out.write("                        <div class=\"feature-item p-4\">\r\n");
      out.write("                            <div class=\"feature-icon mb-3\"><img src=\"/pet/resources/img/chatting.png\"></img></div>\r\n");
      out.write("                            <a href=\"#\" class=\"h4 mb-3\">실시간 채팅</a>\r\n");
      out.write("                            <p class=\"mb-3\">Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repellat deleniti necessitatibus</p>\r\n");
      out.write("                            <a href=\"#\" class=\"btn text-secondary\">Read More <i class=\"fa fa-angle-right\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-6 col-xl-3 wow fadeInUp\" data-wow-delay=\"0.4s\">\r\n");
      out.write("                        <div class=\"feature-item p-4\">\r\n");
      out.write("                            <div class=\"feature-icon mb-3\"><img src=\"/pet/resources/img/petfoot.png\"></img></div>\r\n");
      out.write("                            <a href=\"#\" class=\"h4 mb-3\">나랑 맞는 반려동물은 ?</a>\r\n");
      out.write("                            <p class=\"mb-3\">Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repellat deleniti necessitatibus</p>\r\n");
      out.write("                            <a href=\"#\" class=\"btn text-secondary\">Read More <i class=\"fa fa-angle-right\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-6 col-xl-3 wow fadeInUp\" data-wow-delay=\"0.6s\">\r\n");
      out.write("                        <div class=\"feature-item p-4\">\r\n");
      out.write("                            <div class=\"feature-icon mb-3\"><img src=\"/pet/resources/img/videocam.png\"></img></div>\r\n");
      out.write("                            <a href=\"#\" class=\"h4 mb-3\">화상면담</a>\r\n");
      out.write("                            <p class=\"mb-3\">Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repellat deleniti necessitatibus</p>\r\n");
      out.write("                            <a href=\"#\" class=\"btn text-secondary\">Read More <i class=\"fa fa-angle-right\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-6 col-xl-3 wow fadeInUp\" data-wow-delay=\"0.8s\">\r\n");
      out.write("                        <div class=\"feature-item p-4\">\r\n");
      out.write("                            <div class=\"feature-icon mb-3\"><img src=\"/pet/resources/img/giveheart.png\"></img></div>\r\n");
      out.write("                            <a href=\"#\" class=\"h4 mb-3\">입양후기</a>\r\n");
      out.write("                            <p class=\"mb-3\">Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repellat deleniti necessitatibus</p>\r\n");
      out.write("                            <a href=\"#\" class=\"btn text-secondary\">Read More <i class=\"fa fa-angle-right\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- feature End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <!-- Copyright Start -->\r\n");
      out.write("        <div class=\"container-fluid copyright py-4\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row g-4 align-items-center\">\r\n");
      out.write("                    <div class=\"col-md-6 text-center text-md-start mb-md-0\">\r\n");
      out.write("                        <span class=\"text-body\"><a href=\"#\" class=\"border-bottom text-white\"><i class=\"fas fa-copyright text-light me-2\"></i>Happynimal</a>, All right reserved.</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6 text-center text-md-end text-body\">\r\n");
      out.write("                        <!--/*** This template is free as long as you keep the below author’s credit link/attribution link/backlink. ***/-->\r\n");
      out.write("                        <!--/*** If you'd like to use the template without the below author’s credit link/attribution link/backlink, ***/-->\r\n");
      out.write("                        <!--/*** you can purchase the Credit Removal License from \"https://htmlcodex.com/credit-removal\". ***/-->\r\n");
      out.write("                        Designed By <a class=\"border-bottom text-white\" href=\"https://htmlcodex.com\">HTML Codex</a> Distributed By <a class=\"border-bottom text-white\" href=\"https://themewagon.com\">ThemeWagon</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Copyright End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Back to Top -->\r\n");
      out.write("        <a href=\"#\" class=\"btn btn-secondary btn-lg-square rounded-circle back-to-top\"><i class=\"fa fa-arrow-up\"></i></a>   \r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    <!-- JavaScript Libraries -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"/pet/static/lib/wow/wow.min.js\"></script>\r\n");
      out.write("    <script src=\"/pet/resources/lib/easing/easing.min.js\"></script>\r\n");
      out.write("    <script src=\"/pet/resources/lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"/pet/resources/lib/counterup/counterup.min.js\"></script>\r\n");
      out.write("    <script src=\"/pet/resources/lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"/pet/resources/js/main.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
