/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-11-08 07:58:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.info;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class shelterinfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1731031435000L));
    _jspx_dependants.put("jar:file:/C:/class/code/springProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Pets/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write(" \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<style>\n");
      out.write("	#title {\n");
      out.write("		text-align: center;\n");
      out.write("		margin-top: 50px;\n");
      out.write("		margin-bottom: 50px;\n");
      out.write("	}\n");
      out.write("	#map {\n");
      out.write("	 	display: flex;\n");
      out.write(" 		justify-content: center; /* 가로 중앙 정렬 */\n");
      out.write(" 		margin: 80px;\n");
      out.write("		width:600px;\n");
      out.write("		height:600px;\n");
      out.write("		 \n");
      out.write("	}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <title>Happynimal</title>\n");
      out.write("        <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\n");
      out.write("        <meta content=\"\" name=\"keywords\">\n");
      out.write("        <meta content=\"\" name=\"description\">\n");
      out.write("        <link rel=\"icon\" href=\"/pet/resources/img/favicon.png\">\n");
      out.write("        <!-- Google Web Fonts -->\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("        <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css2?family=Open+Sans:ital,wdth,wght@0,75..100,300..800;1,75..100,300..800&family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap\" rel=\"stylesheet\"> \n");
      out.write("\n");
      out.write("        <!-- Icon Font Stylesheet -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.15.4/css/all.css\"/>\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("        <!-- Libraries Stylesheet -->\n");
      out.write("        <link href=\"/pet/resources/lib/animate/animate.min.css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"/pet/resources/lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- Customized Bootstrap Stylesheet -->\n");
      out.write("        <link href=\"/pet/resources/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("        <!-- Template Stylesheet -->\n");
      out.write("        <link href=\"/pet/resources/css/style.css\" rel=\"stylesheet\">\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("\n");
      out.write("       <!-- Spinner Start -->\n");
      out.write("       <div id=\"spinner\" class=\"show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center\">\n");
      out.write("        <div class=\"spinner-border text-primary\" style=\"width: 3rem; height: 3rem;\" role=\"status\">\n");
      out.write("            <span class=\"sr-only\">Loading...</span>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- Spinner End -->\n");
      out.write("\n");
      out.write("    <!-- Navbar & Hero Start -->\n");
      out.write("    <div class=\"container-fluid position-relative p-0\">\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-light px-4 px-lg-5 py-3 py-lg-0\">\n");
      out.write("            <a href=\"/pet/index.do\" class=\"navbar-brand p-0\">\n");
      out.write("                <h1 class=\"text-primary\"><img src=\"/pet/resources/img/logo2.png\"></img>Happynimal</h1>\n");
      out.write("                <!-- <img src=\"img/logo.png\" alt=\"Logo\"> -->\n");
      out.write("            </a>\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarCollapse\">\n");
      out.write("                <span class=\"fa fa-bars\"></span>\n");
      out.write("            </button>\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarCollapse\">\n");
      out.write("                <div class=\"navbar-nav ms-auto py-0\">\n");
      out.write("                    <a href=\"/pet/index.do\" class=\"nav-item nav-link\">Home</a>\n");
      out.write("                        <a href=\"/pet/about.do\" class=\"nav-item nav-link\">소개</a>\n");
      out.write("                        <div class=\"nav-item dropdown\">\n");
      out.write("                            <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">입양</a>\n");
      out.write("                            <div class=\"dropdown-menu m-0\">\n");
      out.write("                                <a href=\"/pet/adoptioninfo.do\" class=\"dropdown-item\">입양안내</a>\n");
      out.write("                                <a href=\"/pet/petboard.do\" class=\"dropdown-item\">기다리는 친구들</a>\n");
      out.write("                                <a href=\"/pet/applicationadoption.do\" class=\"dropdown-item\">입양신청</a>\n");
      out.write("                                <a href=\"/pet/review.do\" class=\"dropdown-item\">입양후기</a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        \n");
      out.write("        \n");
      out.write("                        <div class=\"nav-item dropdown\">\n");
      out.write("                            <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">활동</a>\n");
      out.write("                            <div class=\"dropdown-menu m-0\">\n");
      out.write("                                <a href=\"/pet/volunteerinfo.do\" class=\"dropdown-item\">봉사활동 안내</a>\n");
      out.write("                                <a href=\"/pet/volunteerboard.do\" class=\"dropdown-item\">봉사활동 모집</a>\n");
      out.write("                                <a href=\"/pet/missingboard.do\" class=\"dropdown-item\">실종 게시판</a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <a href=\"/pet/shelter.do\" class=\"nav-item nav-link active\">보호소 및 병원</a>\n");
      out.write("                        <a href=\"/pet/donation.do\" class=\"nav-item nav-link\">후원</a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"d-none d-xl-flex me-3\">\n");
      out.write("                    <div class=\"d-flex flex-column pe-3 border-end border-primary\">\n");
      out.write("                       \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <a href=\"\" class=\"btn btn-primary rounded-pill d-inline-flex flex-shrink-0 py-2 px-4\">로그인</a>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("\n");
      out.write("            <!-- Header Start -->\n");
      out.write("            <div class=\"container-fluid bg-breadcrumb\">\n");
      out.write("                <div class=\"container text-center py-5\" style=\"max-width: 900px;\">\n");
      out.write("                    <h4 class=\"text-white display-4 mb-4 wow fadeInDown\" data-wow-delay=\"0.1s\">보호소 및 병원</h4>\n");
      out.write("                    <ol class=\"breadcrumb d-flex justify-content-center mb-0 wow fadeInDown\" data-wow-delay=\"0.3s\">\n");
      out.write("                        <li class=\"breadcrumb-item\"><a href=\"/pet/index.do\">Home</a></li>\n");
      out.write("                        <li class=\"breadcrumb-item\"><a href=\"#\">Pages</a></li>\n");
      out.write("                        <li class=\"breadcrumb-item active text-primary\">Shelter and Hospital</li>\n");
      out.write("                    </ol>    \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- Header End -->\n");
      out.write("        </div>\n");
      out.write("        <!-- Navbar & Hero End -->\n");
      out.write("\n");
      out.write("        <!-- Modal Search Start -->\n");
      out.write("        <div class=\"modal fade\" id=\"searchModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("            <div class=\"modal-dialog modal-fullscreen\">\n");
      out.write("                <div class=\"modal-content rounded-0\">\n");
      out.write("                    <div class=\"modal-header\">\n");
      out.write("                        <h4 class=\"modal-title mb-0\" id=\"exampleModalLabel\">Search by keyword</h4>\n");
      out.write("                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"modal-body d-flex align-items-center\">\n");
      out.write("                        <div class=\"input-group w-75 mx-auto d-flex\">\n");
      out.write("                            <input type=\"search\" class=\"form-control p-3\" placeholder=\"keywords\" aria-describedby=\"search-icon-1\">\n");
      out.write("                            <span id=\"search-icon-1\" class=\"input-group-text btn border p-3\"><i class=\"fa fa-search text-white\"></i></span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Modal Search End -->\n");
      out.write("\n");
      out.write("        <!-- 지도 -->\n");
      out.write("        <!-- style=\"text-align: center -->\n");
      out.write("        <h1 id=title>보호소 병원 안내</h1>\n");
      out.write("        <div id=\"map\" ></div>\n");
      out.write("        \n");
      out.write("        <section class=\"notice\">\n");
      out.write("		  <div class=\"page-title\">\n");
      out.write("		        <div class=\"container\">\n");
      out.write("		            <h3>리스트</h3>\n");
      out.write("		        </div>\n");
      out.write("		    </div>\n");
      out.write("   \n");
      out.write("  <!-- board list area -->\n");
      out.write("\n");
      out.write("    <div id=\"board-list\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <table class=\"board-table\">\n");
      out.write("                <thead>\n");
      out.write("                <tr>\n");
      out.write("                    <th scope=\"col\" class=\"th-num\">번호</th>\n");
      out.write("                    <th scope=\"col\" class=\"th-title\">이름</th>\n");
      out.write("                    <th scope=\"col\" class=\"th-date\">전화번호</th>\n");
      out.write("                </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                \n");
      out.write("                ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("        <!-- 지도End -->\n");
      out.write("        \n");
      out.write("        \n");
      out.write("\n");
      out.write("        \n");
      out.write("\n");
      out.write("        \n");
      out.write("        <!-- Copyright Start -->\n");
      out.write("        <div class=\"container-fluid copyright py-4\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row g-4 align-items-center\">\n");
      out.write("                    <div class=\"col-md-6 text-center text-md-start mb-md-0\">\n");
      out.write("                        <span class=\"text-body\"><a href=\"#\" class=\"border-bottom text-white\"><i class=\"fas fa-copyright text-light me-2\"></i>Your Site Name</a>, All right reserved.</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-6 text-center text-md-end text-body\">\n");
      out.write("                        <!--/*** This template is free as long as you keep the below author’s credit link/attribution link/backlink. ***/-->\n");
      out.write("                        <!--/*** If you'd like to use the template without the below author’s credit link/attribution link/backlink, ***/-->\n");
      out.write("                        <!--/*** you can purchase the Credit Removal License from \"https://htmlcodex.com/credit-removal\". ***/-->\n");
      out.write("                        Designed By <a class=\"border-bottom text-white\" href=\"https://htmlcodex.com\">HTML Codex</a> Distributed By <a class=\"border-bottom text-white\" href=\"https://themewagon.com\">ThemeWagon</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Copyright End -->\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!-- Back to Top -->\n");
      out.write("        <a href=\"#\" class=\"btn btn-secondary btn-lg-square rounded-circle back-to-top\"><i class=\"fa fa-arrow-up\"></i></a>   \n");
      out.write("\n");
      out.write("        \n");
      out.write("    <!-- JavaScript Libraries -->\n");
      out.write("    <script type=\"text/javascript\" src=\"https://dapi.kakao.com/v2/maps/sdk.js?appkey=b59a3e33989133235f6e5dd1256b5469\"></script>\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js\"></script>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("    <script src=\"/pet/resources/lib/wow/wow.min.js\"></script>\n");
      out.write("    <script src=\"/pet/resources/lib/easing/easing.min.js\"></script>\n");
      out.write("    <script src=\"/pet/resources/lib/waypoints/waypoints.min.js\"></script>\n");
      out.write("    <script src=\"/pet/resources/lib/counterup/counterup.min.js\"></script>\n");
      out.write("    <script src=\"/pet/resources/lib/owlcarousel/owl.carousel.min.js\"></script>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("\n");
      out.write("    <!-- Template Javascript -->\n");
      out.write("    <script src=\"/pet/resources/js/main.js\"></script>\n");
      out.write("    	<script>\n");
      out.write("		var container = document.getElementById('map'); //지도를 담을 영역의 DOM 레퍼런스\n");
      out.write("		\n");
      out.write("		var options = { //지도를 생성할 때 필요한 기본 옵션\n");
      out.write("			center: new kakao.maps.LatLng(33.450701, 126.570667), //지도의 중심좌표.\n");
      out.write("			level: 3 //지도의 레벨(확대, 축소 정도)\n");
      out.write("		};\n");
      out.write("	\n");
      out.write("		var map = new kakao.maps.Map(container, options); //지도 생성 및 객체 리턴\n");
      out.write("		\n");
      out.write("		//마커 표시할 위도,경도들\n");
      out.write("		var position = {\n");
      out.write("				\n");
      out.write("		};\n");
      out.write("		\n");
      out.write("		//마커 표시\n");
      out.write("		var markerImage = new kakao.maps.MarkerImage(\n");
      out.write("			'/pet/resource/img/marker.png',\n");
      out.write("			new kakao.maps.Size(48, 48),\n");
      out.write("			{\n");
      out.write("				offset: new kakao.maps.Point(32, 64)\n");
      out.write("			}\n");
      out.write("		);\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		//마커 표시하는 스크립트\n");
      out.write("		position.forEach(function(position) {\n");
      out.write("			var markerPosition = new kakao.maps.LatLng(position.lat, position.lng);\n");
      out.write("			var marker = new kakao.maps.Marker({\n");
      out.write("				position: markerPosition,\n");
      out.write("				titile: position.title\n");
      out.write("			});\n");
      out.write("			maker.setMap(map);\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("	\n");
      out.write("	</script>\n");
      out.write("    </body>\n");
      out.write("\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/info/shelterinfo.jsp(166,16) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/info/shelterinfo.jsp(166,16) '${shelter}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${shelter}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/info/shelterinfo.jsp(166,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("ShelterDTO");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("	                <tr>\n");
            out.write("	                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ShelterDTO.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("	                    <th>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ShelterDTO.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</th>\n");
            out.write("	                    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ShelterDTO.telephone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("	                </tr>\n");
            out.write("	             ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
